/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unip.chatclient.view;

/**
 *
 * @author Felipe
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Titulocad = new javax.swing.JPanel();
        lbl_txt1 = new javax.swing.JLabel();
        lbl_txt2 = new javax.swing.JLabel();
        figura1 = new javax.swing.JLabel();
        jP_Infos = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        jT_Nome = new javax.swing.JTextField();
        lbl_data = new javax.swing.JLabel();
        datadenasc = new javax.swing.JFormattedTextField();
        lbl_usuario = new javax.swing.JLabel();
        jT_Usuario = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        lbl_confirmsenha = new javax.swing.JLabel();
        password_Senha = new javax.swing.JPasswordField();
        password_Confirmsenha = new javax.swing.JPasswordField();
        Bt_Confirmar = new javax.swing.JButton();
        Bt_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jP_Titulocad.setBackground(new java.awt.Color(0, 153, 51));

        lbl_txt1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        lbl_txt1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt1.setText("Criar uma conta");

        lbl_txt2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbl_txt2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt2.setText("É rápido e muito fácil.");

        figura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unip/chatclient/view/img/novousuario.png"))); // NOI18N

        lbl_nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_nome.setText("Digite seu Nome:");

        jT_Nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_Nome.setText("Fulano de Tal");
        jT_Nome.setToolTipText("Digite seu nome Completo!");

        lbl_data.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_data.setText("Data de Nascimento:");

        datadenasc.setColumns(1);
        datadenasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        datadenasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datadenasc.setText("03/03/2000");
        datadenasc.setToolTipText("Preencha a data com as \"/\".");

        lbl_usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_usuario.setText("Usuário:");

        jT_Usuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jT_Usuario.setText("Tal_de_Fulano");
        jT_Usuario.setToolTipText("Esse nome será utilizado para as proximas vezes que for entrer no sistema.");

        lbl_senha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_senha.setText("Digite sua Senha:");

        lbl_confirmsenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_confirmsenha.setText("Confirme a Senha:");

        password_Senha.setText("Androidpythonjava");
        password_Senha.setToolTipText("");

        password_Confirmsenha.setText("androidpythonjava");
        password_Confirmsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_ConfirmsenhaActionPerformed(evt);
            }
        });

        Bt_Confirmar.setBackground(new java.awt.Color(0, 153, 51));
        Bt_Confirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Bt_Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Confirmar.setText("Cadastre-se");
        Bt_Confirmar.setContentAreaFilled(false);
        Bt_Confirmar.setOpaque(true);
        Bt_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ConfirmarActionPerformed(evt);
            }
        });

        Bt_Cancelar.setBackground(new java.awt.Color(255, 51, 0));
        Bt_Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Bt_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Cancelar.setText("Cancelar");
        Bt_Cancelar.setContentAreaFilled(false);
        Bt_Cancelar.setOpaque(true);
        Bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_InfosLayout = new javax.swing.GroupLayout(jP_Infos);
        jP_Infos.setLayout(jP_InfosLayout);
        jP_InfosLayout.setHorizontalGroup(
            jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_InfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_InfosLayout.createSequentialGroup()
                        .addComponent(lbl_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Nome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_InfosLayout.createSequentialGroup()
                        .addComponent(lbl_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbl_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datadenasc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_InfosLayout.createSequentialGroup()
                        .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_InfosLayout.createSequentialGroup()
                                .addComponent(lbl_senha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password_Senha))
                            .addGroup(jP_InfosLayout.createSequentialGroup()
                                .addComponent(lbl_confirmsenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password_Confirmsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(176, 176, 176)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_InfosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Bt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jP_InfosLayout.setVerticalGroup(
            jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_InfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(jT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_data)
                    .addComponent(datadenasc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario)
                    .addComponent(jT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha)
                    .addComponent(password_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confirmsenha)
                    .addComponent(password_Confirmsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jP_InfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jP_TitulocadLayout = new javax.swing.GroupLayout(jP_Titulocad);
        jP_Titulocad.setLayout(jP_TitulocadLayout);
        jP_TitulocadLayout.setHorizontalGroup(
            jP_TitulocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TitulocadLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jP_TitulocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jP_TitulocadLayout.createSequentialGroup()
                        .addComponent(lbl_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(figura1)
                .addGap(37, 37, 37))
            .addComponent(jP_Infos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_TitulocadLayout.setVerticalGroup(
            jP_TitulocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TitulocadLayout.createSequentialGroup()
                .addGroup(jP_TitulocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_TitulocadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(figura1))
                    .addGroup(jP_TitulocadLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_txt1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Infos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Titulocad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Titulocad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_CancelarActionPerformed

    private void password_ConfirmsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_ConfirmsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_ConfirmsenhaActionPerformed

    private void Bt_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Cancelar;
    private javax.swing.JButton Bt_Confirmar;
    private javax.swing.JFormattedTextField datadenasc;
    private javax.swing.JLabel figura1;
    private javax.swing.JPanel jP_Infos;
    private javax.swing.JPanel jP_Titulocad;
    private javax.swing.JTextField jT_Nome;
    private javax.swing.JTextField jT_Usuario;
    private javax.swing.JLabel lbl_confirmsenha;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_txt1;
    private javax.swing.JLabel lbl_txt2;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField password_Confirmsenha;
    private javax.swing.JPasswordField password_Senha;
    // End of variables declaration//GEN-END:variables
}
