DROP PROCEDURE SP_USUARIO_IN;
DELIMITER $$
CREATE PROCEDURE SP_USUARIO_IN (uLogin VARCHAR(50), uNome VARCHAR(50), uPassword VARCHAR(50))
BEGIN 
		INSERT INTO USUARIO (USU_STR_LOGIN, USU_STR_NOME, USU_STR_PASSWORD) VALUES (uLogin, uNome, uPassword);
END $$
DELIMITER ;
