DROP PROCEDURE SP_USUARIO_IN;
DELIMITER $$
CREATE PROCEDURE SP_USUARIO_IN (uLogin VARCHAR(50), uNome VARCHAR(50), uPassword VARCHAR(50))
BEGIN 
		INSERT INTO USUARIO (USU_STR_LOGIN, USU_STR_NOME, USU_STR_PASSWORD) VALUES (uLogin, uNome, uPassword);
END $$
DELIMITER ;

DROP PROCEDURE SP_MENSSAGEM_IN
DELIMITER $$
CREATE PROCEDURE SP_MENSSAGEM_IN (mMensagem VARCHAR(600), uRemetente VARCHAR(50), uDestinatario VARCHAR(50))
BEGIN
	INSERT INTO MENSAGEM (MEN_STR_MENSAGEM, USU_STR_REMETENTE, USU_STR_DESTINATARIO) VALUES (mMensagem, uRemetente, uDestinatario);
END$$
DELIMITER ; 
