CREATE SCHEMA APSCHAT;
DROP TABLE MENSAGEM;
DROP TABLE USUARIO;
CREATE TABLE USUARIO(
USU_INT_ID INT NOT NULL AUTO_INCREMENT,
USU_STR_LOGIN VARCHAR (50) NOT NULL UNIQUE,
USU_STR_NOME VARCHAR (50) NOT NULL,
USU_STR_PASSWORD VARCHAR (50) NOT NULL,
CONSTRAINT PK_USUARIO_ID PRIMARY KEY (USU_INT_ID)
);
SELECT * FROM USUARIO;

CREATE TABLE MENSAGEM(
MEN_INT_ID INT NOT NULL AUTO_INCREMENT,
MEN_STR_MENSAGEM VARCHAR (600),
USU_INT_REMETENTE_ID INT NOT NULL,
USU_INT_DESTINATARIO_ID INT NOT NULL,
MEN_DATE_HORA_MENSAGEM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_MENSAGEM_ID PRIMARY KEY (MEN_INT_ID),
CONSTRAINT FK_USUARIO_REMETENTE_ID FOREIGN KEY (USU_INT_REMETENTE_ID) REFERENCES USUARIO (USU_INT_ID),
CONSTRAINT FK_USUARIO_DESTINATARIO_ID FOREIGN KEY (USU_INT_DESTINATARIO_ID) REFERENCES USUARIO (USU_INT_ID)
);
SELECT * FROM MENSAGEM;